### ISSUE TITLE
Comments from Ari Keränen on Draft version -06

### ISSUE THREAD

**Issue by daveoran** [icnrg/draft-irtf-icnrg-terminology#10]
4.5. (Remote Procedure Call). It seems to just repeat verbatim parts of section 3.3 without giving much useful extra information.
In looking this over, I (mostly) agree. I think this section could be removed without losing much useful. In fact, there’s been a lot of work done on remote invocation with ICN since all this was written and pretty much obsoletes anything we would have said here. Given the increasing importance of distributed computing stuff for ICN, what I propose here is to get rid fo the individual definitions, retain the section heading, and replace the text with a general statement about the terminology being applicable to RPC, with references to some of the recent work (most notably RICE from ICN’18, CFN from ICN’19 and the design for network management paper also from ICN’19. Unless I hear otherwise from ICNRG folks or IRSG folks, this is what I’ll do.
Would be useful to provide references for NDN and CCNx.
Yes. Already in the update plan.
The asterisks around the terms and three empty lines before common aliases looked weird to me. I'd remove the asterisks and have just single empty line before the common aliases.
This is an xml2rfc artifact for how the .txt rendering is done for XML constructs like <spanx>. The HTML output is much prettier. I’m going to leave this - maybe the version3 text renderer will be better :-)
Section 2: colon missing for "Packet and Content Names"
Will fix.
Typo in Section 3.4: sigtnature
Will fix.

**Comment by dku** [comment]
Sounds good (approach to RPC)

**Comment by daveoran** [comment]
I decided to have two sections, one on RPC and a second on Pub/Sub. In the latter I’ll reference the Nichols paper and dig up the earlier pub/sub paper from ICN.
