### ISSUE TITLE
on-patch in-network caching

### ISSUE THREAD

**Issue by yoursunny** [icnrg/draft-irtf-icnrg-terminology#5]
I’ve never heard the terms “on-**patch** in-network caching” and “off-**patch** in-network storage”. Should they be “on-path” and “off-path” instead?

**Comment by daveoran** [comment]
Yeah, it’s a typo…

On 14 Dec 2017, at 22:47, yoursunny wrote:

> I’ve never heard the terms “on-**patch** in-network caching” and “off-**patch** in-network storage”. Should they be “on-path” and “off-path” instead?
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icnrg/draft-irtf-icnrg-terminology/issues/5



DaveO
